version: "3"

tasks:
  build:
    cmds:
      - wails build
    dir: trequer
    deps:
      - wails

  dev:
    cmds:
      - wails dev
    dir: trequer
    deps:
      - wails

  frontend:lint:
    cmds:
      - npx prettier --check .
      - npx eslint .
      - npx vue-tsc --build --force
    dir: trequer/frontend

  frontend:format:
    cmds:
      - npx prettier --write .
    dir: trequer/frontend

  wails:
    internal: true
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest
    dir: trequer
    generates:
      - _go/bin/wails
